version: '3'

services:
  app:
    build: ./app
    container_name: app
    ports:
      - "3000:3000"
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 30s sh -c "npm install && node index.js"
    volumes:
      - ./app:/usr/src/app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped


  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nodedb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5